export const popularJobData = [
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "EpNJ1XbFJ4zyiey4AAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-at-dice-3815839406",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6385,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/react-developer-at-dice-3815839406",
        is_direct: false,
      },
    ],
    job_description:
      "Dice is the leading career destination for tech experts at every stage of their careers. Our client, Jobot, is seeking the following. Apply via Dice today!\n\nThis Jobot Job is hosted by: Dan Dungy\n\nAre you a fit? Easy Apply now by clicking the \"Apply Now\" button and sending us your resume.\n\nSalary: $90,000 - $110,000 per year\n\nA bit about us:\n\nWe're a very large privately held bank.\n\nWhy join us?\n\nWe have a great culture on our team and we're building exciting products in our industry.\n\nJob Details\n\nJob Details:\n\nWe are seeking a talented and experienced React Developer to join our dynamic team. This is a fantastic opportunity to contribute to the development of our innovative banking solutions that are transforming the industry. The successful candidate will be responsible for creating and implementing visually appealing, user-friendly interfaces that will enhance our customers' experience. As a React Developer, you will work closely with cross-functional teams to develop and upgrade our mortgage systems. The role is ideal for someone who thrives in a fast-paced, challenging environment and has a passion for technology and its ability to drive efficiency and effectiveness.\n\nResponsibilities:\n• Develop new user-facing features using React Native.\n• Build reusable components and front-end libraries for future use.\n• Translate designs and wireframes into high-quality code.\n• Optimize components for maximum performance across a vast array of web-capable devices and browsers.\n• Collaborate with the product team to design innovative solutions to meet market needs.\n• Work closely with back-end developers to integrate user-facing elements with server-side logic.\n• Participate in code reviews to maintain a high-quality code base.\n• Test software to ensure responsiveness and efficiency.\n• Troubleshoot, debug and upgrade software.\n• Create security and data protection settings.\n\nQualifications:\n• Bachelor's degree in Computer Science, Information Technology, or a related field.\n• 3+ years of experience in React Native and other popular frameworks.\n• Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model.\n• Thorough understanding of React.js and its core principles.\n• Experience with popular React.js workflows (such as Flux or Redux).\n• Knowledge of .NET and MVC frameworks.\n• Proficiency in TypeScript.\n• Familiarity with modern front-end build pipelines and tools.\n• Experience with common front-end development tools such as Babel, Webpack, NPM, etc.\n• Ability to understand business requirements and translate them into technical requirements.\n• A knack for benchmarking and optimization.\n• Familiarity with code versioning tools such as Git, SVN, and Mercurial.\n• Strong problem-solving skills, attention to detail, and a team player.\n• Excellent communication skills, both verbal and written.\n\nInterested in hearing more? Easy Apply now by clicking the \"Apply Now\" button.",
    job_is_remote: true,
    job_posted_at_timestamp: 1706305072,
    job_posted_at_datetime_utc: "2024-01-26T21:37:52.000Z",
    job_city: "Oklahoma City",
    job_state: "OK",
    job_country: "US",
    job_latitude: 35.46756,
    job_longitude: -97.516426,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=EpNJ1XbFJ4zyiey4AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-02-25T21:37:52.000Z",
    job_offer_expiration_timestamp: 1708897072,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "The role is ideal for someone who thrives in a fast-paced, challenging environment and has a passion for technology and its ability to drive efficiency and effectiveness",
        "Bachelor's degree in Computer Science, Information Technology, or a related field",
        "3+ years of experience in React Native and other popular frameworks",
        "Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model",
        "Thorough understanding of React.js and its core principles",
        "Experience with popular React.js workflows (such as Flux or Redux)",
        "Knowledge of .NET and MVC frameworks",
        "Proficiency in TypeScript",
        "Familiarity with modern front-end build pipelines and tools",
        "Experience with common front-end development tools such as Babel, Webpack, NPM, etc",
        "Ability to understand business requirements and translate them into technical requirements",
        "A knack for benchmarking and optimization",
        "Familiarity with code versioning tools such as Git, SVN, and Mercurial",
        "Strong problem-solving skills, attention to detail, and a team player",
        "Excellent communication skills, both verbal and written",
      ],
      Responsibilities: [
        "The successful candidate will be responsible for creating and implementing visually appealing, user-friendly interfaces that will enhance our customers' experience",
        "As a React Developer, you will work closely with cross-functional teams to develop and upgrade our mortgage systems",
        "Develop new user-facing features using React Native",
        "Build reusable components and front-end libraries for future use",
        "Translate designs and wireframes into high-quality code",
        "Optimize components for maximum performance across a vast array of web-capable devices and browsers",
        "Collaborate with the product team to design innovative solutions to meet market needs",
        "Work closely with back-end developers to integrate user-facing elements with server-side logic",
        "Participate in code reviews to maintain a high-quality code base",
        "Test software to ensure responsiveness and efficiency",
        "Troubleshoot, debug and upgrade software",
        "Create security and data protection settings",
      ],
      Benefits: ["Salary: $90,000 - $110,000 per year"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "519130",
    job_naics_name:
      "Internet Publishing and Broadcasting and Web Search Portals",
  },
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "LinkedIn",
    job_id: "W8QDKlSGpdYlCv5qAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "React Developer (Front-End)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/react-developer-front-end-at-dice-3815838634",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6385,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/react-developer-front-end-at-dice-3815838634",
        is_direct: false,
      },
      {
        publisher: "Jooble",
        apply_link: "https://jooble.org/jdp/8053193281253746231",
        is_direct: false,
      },
    ],
    job_description:
      "Dice is the leading career destination for tech experts at every stage of their careers. Our client, Lorven Technologies, Inc., is seeking the following. Apply via Dice today!\n\nJob Title: React Developer (Front-End)\n\nLocation: Remote\n\nDuration: Fulltime\n\nJob Overview:\n\nWe are seeking a skilled React Developer with a strong focus on front-end development to join our dynamic team. The ideal candidate will be responsible for designing and implementing user interfaces for web applications using React.js. As a React Developer, you will collaborate with cross-functional teams to define, design, and ship new features, ensuring a seamless and responsive user experience.\n\nKey Responsibilities:\n• Develop and maintain user interfaces for web applications using React.js\n• Collaborate with product managers and other stakeholders to gather and define requirements\n• Translate design wireframes and mockups into high-quality code\n• Write clean, efficient, and maintainable code\n• Optimize components for maximum performance across various web-capable devices and browsers\n• Work closely with back-end developers to integrate front-end and back-end logic\n• Participate in code reviews and provide constructive feedback to peers\n• Stay up-to-date with the latest industry trends and technologies to ensure our applications remain cutting-edge\n• Troubleshoot and debug issues, and provide timely resolution to reported problems\n\nQualifications:\n• Proven experience as a React Developer or similar role\n• Solid understanding of React.js and its core principles\n• Experience with popular React.js workflows (such as Redux)\n• Familiarity with RESTful APIs and modern front-end build pipelines and tools\n• Proficient understanding of web markup, including HTML5, CSS3\n• Strong understanding of responsive design and cross-browser compatibility\n• Excellent problem-solving and communication skills\n• Ability to work well in a collaborative team environment\n• Bachelor's degree in Computer Science or a related field (or equivalent work experience)\n\nNice-to-Have:\n• Experience with back-end technologies (Node.js, Express, etc.)\n• Knowledge of code versioning tools, such as Git\n• Familiarity with Agile/Scrum development methodologies",
    job_is_remote: true,
    job_posted_at_timestamp: 1706305067,
    job_posted_at_datetime_utc: "2024-01-26T21:37:47.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=W8QDKlSGpdYlCv5qAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-02-25T21:37:47.000Z",
    job_offer_expiration_timestamp: 1708897067,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Proven experience as a React Developer or similar role",
        "Solid understanding of React.js and its core principles",
        "Experience with popular React.js workflows (such as Redux)",
        "Familiarity with RESTful APIs and modern front-end build pipelines and tools",
        "Proficient understanding of web markup, including HTML5, CSS3",
        "Strong understanding of responsive design and cross-browser compatibility",
        "Excellent problem-solving and communication skills",
        "Ability to work well in a collaborative team environment",
        "Bachelor's degree in Computer Science or a related field (or equivalent work experience)",
        "Experience with back-end technologies (Node.js, Express, etc.)",
        "Knowledge of code versioning tools, such as Git",
        "Familiarity with Agile/Scrum development methodologies",
      ],
      Responsibilities: [
        "As a React Developer, you will collaborate with cross-functional teams to define, design, and ship new features, ensuring a seamless and responsive user experience",
        "Develop and maintain user interfaces for web applications using React.js",
        "Collaborate with product managers and other stakeholders to gather and define requirements",
        "Translate design wireframes and mockups into high-quality code",
        "Write clean, efficient, and maintainable code",
        "Optimize components for maximum performance across various web-capable devices and browsers",
        "Work closely with back-end developers to integrate front-end and back-end logic",
        "Participate in code reviews and provide constructive feedback to peers",
        "Stay up-to-date with the latest industry trends and technologies to ensure our applications remain cutting-edge",
        "Troubleshoot and debug issues, and provide timely resolution to reported problems",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "519130",
    job_naics_name:
      "Internet Publishing and Broadcasting and Web Search Portals",
  },
  {
    employer_name: "EVOLVE",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnug8G71HstpdYHb3D7hSk8T5OUEo4bIC6i8OB&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "tv0WgKZlb22gAgmNAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Senior Front End React Developer/Full Stack",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/senior-front-end-react-developer-full-stack-at-evolve-3815844702",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6797,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/senior-front-end-react-developer-full-stack-at-evolve-3815844702",
        is_direct: false,
      },
    ],
    job_description:
      "Evolve MEP is seeking a senior React developer on a team developing an application which is pivotal for our corporate growth. Candiate must have recent and demonstrable skills with React concepts such as state and hooks. Candidate must have strong communication skills to work with both the technical development team and product management. Candidate will report to management which are developers themselves.\n\nEvolve MEP is based in Atlanta, however this position is completely remote (only a web cam required) with flexible hours available.\n\nQualifications\n• Bachelors (or higher) degree required\n• English as primary language\n• Senior level experience working with React (Kendo experience is a plus)\n• Experience working with .NET backend technologies\n• Must be able to grasp and internalize business goals as they relate to the product\n• Strong communication skills to work effectively within a team of developers (knowledge share), product managers, and QA\n• Must be able to communicate unprompted and articulate problems, roadblocks, and concerns both encountered and anticipated\n• Ability to self-manage time effectively between multiple tasks to provide time estimates, communicate progress, and adhere to reasonable deadlines\n• Write and maintain clear and accurate requirements and code documentation\n• Follow company development standards and practice\n\nCandidate must be a legal US resident with primary residence outside of the following states: CA, IL, NV, NY\n\nSubmission process is through Test Gorilla which asks candidates to upload a resume and perform a basic skills assessment which will take no more than 25 minutes to complete.\n\nTo qualify for consideration, candidates must fully complete the assessment without any use of generative AI.",
    job_is_remote: true,
    job_posted_at_timestamp: 1706305927,
    job_posted_at_datetime_utc: "2024-01-26T21:52:07.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=tv0WgKZlb22gAgmNAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-07-24T21:50:36.000Z",
    job_offer_expiration_timestamp: 1721857836,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: [
      "Full-Stack Development",
      "React.js",
      "Front-End Development",
      ".NET Framework",
      "Kendo",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Candiate must have recent and demonstrable skills with React concepts such as state and hooks",
        "Candidate must have strong communication skills to work with both the technical development team and product management",
        "Bachelors (or higher) degree required",
        "English as primary language",
        "Experience working with .NET backend technologies",
        "Must be able to grasp and internalize business goals as they relate to the product",
        "Strong communication skills to work effectively within a team of developers (knowledge share), product managers, and QA",
        "Must be able to communicate unprompted and articulate problems, roadblocks, and concerns both encountered and anticipated",
        "Ability to self-manage time effectively between multiple tasks to provide time estimates, communicate progress, and adhere to reasonable deadlines",
        "Write and maintain clear and accurate requirements and code documentation",
        "Follow company development standards and practice",
        "Candidate must be a legal US resident with primary residence outside of the following states: CA, IL, NV, NY",
        "Submission process is through Test Gorilla which asks candidates to upload a resume and perform a basic skills assessment which will take no more than 25 minutes to complete",
        "To qualify for consideration, candidates must fully complete the assessment without any use of generative AI",
      ],
    },
    job_job_title: "Senior",
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "BairesDev",
    employer_logo:
      "https://storage.googleapis.com/website-wordpress/uploads/user_profiles/BairesDev-Editorial-Team.png",
    employer_website: "https://www.bairesdev.com",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "ze-F3XhJKaRn0kYCAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: ".NET + React Developer - Remote Work -",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/net-%2B-react-developer-remote-work-at-bairesdev-3814612344",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6797,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/net-%2B-react-developer-remote-work-at-bairesdev-3814612344",
        is_direct: false,
      },
    ],
    job_description:
      "Who We are\n\nBairesDev is proud to be the fastest-growing company in America. With people in five continents and world-class clients, we are only as strong as the multicultural teams at the heart of our business. To consistently deliver the highest quality solutions to our clients, we only hire the Top 1% of the best talents and nurture their professional growth on exciting projects.\n• NET + React Developer at Baires Dev\n\nAs a Senior .NET + React Developer, lead in creating robust solutions using .NET Core, C#, and related technologies. Your expertise will guide the development of scalable applications, mentor junior developers, and innovate within our tech stack, ensuring high-quality software delivery.\n\nResponsibilities\n• Lead the design and development of complex, high-performance .NET applications, meeting business requirements.\n• Mentor junior and semi-senior developers, fostering technical excellence.\n• Make key architectural decisions, contributing to long-term strategic planning of software projects.\n• Oversee code reviews to maintain high standards of code quality and best practices.\n• Evaluate and advocate for the adoption of new .NET technologies and practices.\n• Provide technical insights and recommendations to project managers and other stakeholders.\n\nRequirements\n• 5+ years of experience with .NET.\n• 1+ years of experience with React.\n• Strong understanding of best practices, such as SOLID and clean code, focusing on scalable solutions.\n• Extensive experience with code reviews, writing automated tests, and implementing CI/CD pipelines.\n• Strong expertise in unit testing, integration testing, and maintaining high code coverage.\n• Demonstrated ability to make informed technical decisions and apply the best approach for each use case.\n• IT infrastructure knowledge.\n• Advanced level of English.\n\nHow we do make your work (and your life) easier:\n• 100% remote work.\n• Hardware setup for you to work from home.\n• Flexible hours - make your schedule.\n• Paid parental leave, vacation & holidays.\n• Diverse and multicultural work environment.\n• An innovative environment with the structure and resources of a leading multinational.\n• Excellent compensation — well above the market average.\n• Here you can grow at the speed of your learning curve.\n\nOur people work remotely but with a consistent and robust culture that promotes diversity and teamwork. To continue being the leading software development company in Latin America, we want to ensure that every BairesDev member gets the best growth and professional development opportunities in a diverse, welcoming, and innovative environment.\n\nEvery BairesDev team member brings something unique to our company.\n\nWe want to hear your story. Apply now!",
    job_is_remote: true,
    job_posted_at_timestamp: 1706227200,
    job_posted_at_datetime_utc: "2024-01-26T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: ["paid_time_off"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ze-F3XhJKaRn0kYCAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-02-26T00:13:45.000Z",
    job_offer_expiration_timestamp: 1708906425,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "5+ years of experience with .NET",
        "1+ years of experience with React",
        "Strong understanding of best practices, such as SOLID and clean code, focusing on scalable solutions",
        "Extensive experience with code reviews, writing automated tests, and implementing CI/CD pipelines",
        "Strong expertise in unit testing, integration testing, and maintaining high code coverage",
        "Demonstrated ability to make informed technical decisions and apply the best approach for each use case",
        "IT infrastructure knowledge",
        "Advanced level of English",
      ],
      Responsibilities: [
        "Your expertise will guide the development of scalable applications, mentor junior developers, and innovate within our tech stack, ensuring high-quality software delivery",
        "Lead the design and development of complex, high-performance .NET applications, meeting business requirements",
        "Mentor junior and semi-senior developers, fostering technical excellence",
        "Make key architectural decisions, contributing to long-term strategic planning of software projects",
        "Oversee code reviews to maintain high standards of code quality and best practices",
        "Evaluate and advocate for the adoption of new .NET technologies and practices",
        "Provide technical insights and recommendations to project managers and other stakeholders",
      ],
      Benefits: [
        "100% remote work",
        "Hardware setup for you to work from home",
        "Flexible hours - make your schedule",
        "Paid parental leave, vacation & holidays",
        "Diverse and multicultural work environment",
        "Excellent compensation — well above the market average",
        "Here you can grow at the speed of your learning curve",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "HYNAVYNIfoI3BJldAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Frontend React Developer",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/Frontend-React-Developer_~016939da12ed7e048c/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6857,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/Frontend-React-Developer_~016939da12ed7e048c/",
        is_direct: true,
      },
    ],
    job_description:
      "We are looking for a skilled frontend React developer to create a three-page static website. The website design will be provided, and you will be responsible for implementing the design using React. The website should be responsive and optimized for various devices. The ideal candidate should have experience working with React and have a good understanding of HTML, CSS, and JavaScript. Attention to detail and the ability to follow design guidelines are essential for this role.\n\nRelevant skills:\n\n- React\n\n- HTML\n\n- CSS\n\n- JavaScript",
    job_is_remote: true,
    job_posted_at_timestamp: 1706291328,
    job_posted_at_datetime_utc: "2024-01-26T17:48:48.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=HYNAVYNIfoI3BJldAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ["React", "JavaScript", "CSS", "HTML", "Redux"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "The ideal candidate should have experience working with React and have a good understanding of HTML, CSS, and JavaScript",
        "Attention to detail and the ability to follow design guidelines are essential for this role",
      ],
      Responsibilities: [
        "The website design will be provided, and you will be responsible for implementing the design using React",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Applied Graphics Technologies",
    employer_logo: null,
    employer_website: "http://www.appliedgraphics.com",
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "e3BgBd7qCNcgXxXAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Full Stack React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/full-stack-react-developer-at-applied-graphics-technologies-3813561721",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6879,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/full-stack-react-developer-at-applied-graphics-technologies-3813561721",
        is_direct: false,
      },
      {
        publisher: "Monster",
        apply_link:
          "https://www.monster.com/job-openings/full-stack-react-developer--ff0be513-8681-4975-b965-a0db9b38821b",
        is_direct: true,
      },
      {
        publisher: "Jooble",
        apply_link: "https://jooble.org/jdp/-3575992030886728552",
        is_direct: false,
      },
    ],
    job_description:
      "Job Description\n• Mid Senior candidate /5 - 12 + years of experience\n• Mandatory skills React, React Native, Microservices, Event queue, REST, Node, Java and Okta experience would be a plus.\n• Proven experience as a Full Stack Developer or similar role\n• Experience developing desktop and mobile applications\n• Familiarity with common stacks\n• Knowledge of multiple front-end languages and libraries (eg HTML/ CSS, JavaScript, XML, jQuery)\n• Knowledge of multiple back-end languages and JavaScript frameworks (eg Angular, React, Node js)\n• Familiarity with databases (eg MySQL, MongoDB), web servers (eg Apache) and UI/UX design\n• Excellent communication and teamwork skills\n• Great attention to detail\n• Organizational skills\n• An analytical mind\n• Degree in Computer Science, Statistics or relevant education.",
    job_is_remote: true,
    job_posted_at_timestamp: 1706216312,
    job_posted_at_datetime_utc: "2024-01-25T20:58:32.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=e3BgBd7qCNcgXxXAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-07-23T20:58:33.000Z",
    job_offer_expiration_timestamp: 1721768313,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Mid Senior candidate /5 - 12 + years of experience",
        "Proven experience as a Full Stack Developer or similar role",
        "Experience developing desktop and mobile applications",
        "Familiarity with common stacks",
        "Knowledge of multiple front-end languages and libraries (eg HTML/ CSS, JavaScript, XML, jQuery)",
        "Knowledge of multiple back-end languages and JavaScript frameworks (eg Angular, React, Node js)",
        "Familiarity with databases (eg MySQL, MongoDB), web servers (eg Apache) and UI/UX design",
        "Excellent communication and teamwork skills",
        "Great attention to detail",
        "Organizational skills",
        "An analytical mind",
        "Degree in Computer Science, Statistics or relevant education",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113300",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "B_20UOr5itseJjJXAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React Developer",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01151d7495deb34fe3/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6857,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01151d7495deb34fe3/",
        is_direct: true,
      },
    ],
    job_description:
      "We are looking for a talented React Developer to work on our dashboard project. The ideal candidate should have a strong understanding of React and its components, as well as experience with designing and implementing responsive, user-friendly interfaces.\n\nAbout Us:\n\nAt Deep Breathe, our mission is to revolutionize the field of respiratory disease diagnostics using AI-driven accuracy. We are a team of passionate individuals who strive to make a positive impact in the healthcare industry. Our focus is on developing cutting-edge technology that leverages deep learning algorithms to automate the interpretation of lung ultrasound video clips/images. Our ultimate goal is to enable healthcare professionals, including nurses, EMTs, family doctors, and more, to take advantage of the benefits of lung ultrasound technology without requiring extensive training. With our commitment to innovation and excellence, we aim to redefine lung ultrasound diagnostics, making it more accessible, affordable, and accurate for everyone.\n\nResponsibilities:\n\n- Design and develop responsive, intuitive, and visually appealing dashboard components\n\n- Collaborate with the team to ensure seamless integration with the backend and other components\n\n- Write clean, maintainable code that adheres to best practices\n\n- Optimize the performance and scalability of the dashboard\n\nRequirements:\n\n- Proficiency in React and its component libraries\n\n- Familiarity with modern front-end development tools and frameworks\n\n- Strong understanding of UI/UX principles and design patterns\n\n- Experience with implementing responsive design\n\n- Excellent problem-solving skills and attention to detail\n\n- Strong communication and collaboration skills\n\n- Ability to work independently and meet deadlines\n\n- Experience with integrating third-party libraries and APIs",
    job_is_remote: true,
    job_posted_at_timestamp: 1706293672,
    job_posted_at_datetime_utc: "2024-01-26T18:27:52.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: ["health_insurance"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=B_20UOr5itseJjJXAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ["React", "JavaScript", "CSS", "HTML"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 15,
    job_max_salary: 30,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "The ideal candidate should have a strong understanding of React and its components, as well as experience with designing and implementing responsive, user-friendly interfaces",
        "Proficiency in React and its component libraries",
        "Familiarity with modern front-end development tools and frameworks",
        "Strong understanding of UI/UX principles and design patterns",
        "Excellent problem-solving skills and attention to detail",
        "Strong communication and collaboration skills",
        "Ability to work independently and meet deadlines",
        "Experience with integrating third-party libraries and APIs",
      ],
      Responsibilities: [
        "Design and develop responsive, intuitive, and visually appealing dashboard components",
        "Collaborate with the team to ensure seamless integration with the backend and other components",
        "Write clean, maintainable code that adheres to best practices",
        "Optimize the performance and scalability of the dashboard",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "PvSJOXJQ5TDk-pEnAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title:
      "React Developer required for 1 front-end screen development - Contract to Hire",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/React-Developer-required-for-front-end-screen-development_~01f3a61de28d6308e3/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6857,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/React-Developer-required-for-front-end-screen-development_~01f3a61de28d6308e3/",
        is_direct: true,
      },
    ],
    job_description:
      "Need a react developer to develop 1 screen using any React Library ( Next JS is preferred ). The dashboard is some sort of few components like side menu, header , table and few animations. We want to hire the person for full time in future and starting with a MVP right now.\n\nPlease share your recent past projects and the budget for 1 screen that you can develop. Perfect fit will be given the role of product developer in future. The required figma file will be only shared to selected users based on best price quote and good portfolio.\n\nNote: Please only apply if you can do it before Sunday Morning ( 28 Jan,2024 )",
    job_is_remote: true,
    job_posted_at_timestamp: 1706296812,
    job_posted_at_datetime_utc: "2024-01-26T19:20:12.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=PvSJOXJQ5TDk-pEnAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: [
      "Web Application",
      "Agile Software Development",
      "SQL",
      "React",
      "JavaScript",
      "CSS",
      "HTML",
      "HTML5",
      "React Native",
      "TypeScript",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Responsibilities: [
        "Perfect fit will be given the role of product developer in future",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "PZznNlnvrwd3T-bjAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React.js Developer",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01db43cf8c561b3bc1/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6857,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/React-Developer_~01db43cf8c561b3bc1/",
        is_direct: true,
      },
    ],
    job_description:
      "Looking for a React.js Developer who having strong skill sets in React.js, TypeScript, Electron.js, and also to integrate the Api\n\nThis is a Support tupe of jobs you need to give around 10 hrs a week including saturday and sunday as well\n\nYou need to work on Zoom screensharing\n\nLocation:- India only",
    job_is_remote: true,
    job_posted_at_timestamp: 1706292746,
    job_posted_at_datetime_utc: "2024-01-26T18:12:26.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=PZznNlnvrwd3T-bjAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: [
      "ExpressJS",
      "React",
      "JavaScript",
      "TypeScript",
      "electron.js",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: ["You need to work on Zoom screensharing"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "ySi6xtnNtfVMNQdMAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "React Developer with Mobile and ETL Experience.",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/React-Developer-with-Mobile-and-ETL-Experience_~0189c4fabede65e409/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6857,
    apply_options: [
      {
        publisher: "Upwork",
        apply_link:
          "https://www.upwork.com/freelance-jobs/apply/React-Developer-with-Mobile-and-ETL-Experience_~0189c4fabede65e409/",
        is_direct: true,
      },
    ],
    job_description:
      "We are looking for a skilled React Developer with Mobile and ETL experience for a one-time project. In this role, you will be responsible for developing a responsive user interface using React.js, with a focus on mobile optimization. Additionally, your expertise in Extract, Transform, Load (ETL) processes will be crucial for efficient data integration within the project. The ideal candidate will bring hands-on experience in React development, mobile app design, and data integration to ensure the successful completion of this specific project. If you are a self-motivated developer with a track record of delivering high-quality solutions, we invite you to apply for this short-term opportunity.\n\nRequirements:\n\n1. Proven experience as a React Developer with a portfolio showcasing mobile-optimized applications.\n\n2. Demonstrated expertise in ETL processes for seamless data integration.\n\n3. Strong proficiency in React.js and mobile development principles.\n\n4. Ability to work independently and deliver results within the defined project timeline.\n\n5. Excellent problem-solving skills and attention to detail.\n\n6. Effective communication and collaboration skills to understand project requirements and provide updates on progress.\n\nThis is a one-time job opportunity with a specific focus on React development, mobile optimization, and ETL experience. If you are ready to contribute your skills to a short-term project, we encourage you to apply and be a part of our dynamic team.",
    job_is_remote: true,
    job_posted_at_timestamp: 1706281846,
    job_posted_at_datetime_utc: "2024-01-26T15:10:46.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=ySi6xtnNtfVMNQdMAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: [
      "React",
      "Amazon Web Services",
      "API",
      "PostgreSQL",
      "Big Data",
      "ETL Pipeline",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 40,
    job_max_salary: 85,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "The ideal candidate will bring hands-on experience in React development, mobile app design, and data integration to ensure the successful completion of this specific project",
        "Proven experience as a React Developer with a portfolio showcasing mobile-optimized applications",
        "Demonstrated expertise in ETL processes for seamless data integration",
        "Strong proficiency in React.js and mobile development principles",
        "Ability to work independently and deliver results within the defined project timeline",
        "Excellent problem-solving skills and attention to detail",
        "Effective communication and collaboration skills to understand project requirements and provide updates on progress",
        "This is a one-time job opportunity with a specific focus on React development, mobile optimization, and ETL experience",
      ],
      Responsibilities: [
        "In this role, you will be responsible for developing a responsive user interface using React.js, with a focus on mobile optimization",
        "Additionally, your expertise in Extract, Transform, Load (ETL) processes will be crucial for efficient data integration within the project",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
];
